status = [
  "formatting",
  "clippy (daemon)",
  "clippy (rocket-basicauth)",
  "clippy (rust-embed-rocket)",
  "clippy (taker)",
  "clippy (maker)",
  "clippy (shared-bin)",
  "clippy (daemon-tests)",
  "clippy (tokio-extras)",
  "clippy (xtras)",
  "clippy (bdk-ext)",
  "clippy (model)",
  "clippy (xtra-bitmex-price-feed)",
  "clippy (btsieve)",
  "clippy (bitmex-stream)",
  "clippy (xtra-libp2p)",
  "clippy (xtra-libp2p-ping)",
  "clippy (sqlite-db)",
  "clippy (xtra-libp2p-offer)",
  "clippy (quiet-spans)",
  "clippy (vergen-version)",
  "clippy (xtra-libp2p-rollover)",
  "lint-commits",
  "frontend (maker)",
  "frontend (taker)",
  "run-tests (1, ubuntu-latest)",
  "run-tests (2, ubuntu-latest)",
  "run-tests (3, ubuntu-latest)",
  "run-tests (4, ubuntu-latest)",
  "smoke_test (ubuntu-latest)",
  "smoke_test (macos-12)",
  "daemons_arm_build",
  "sqlx-db-check",
]
