status = [
  "formatting",
  "clippy (daemon)",
  "clippy (rocket-basicauth)",
  "clippy (rust-embed-rocket)",
  "clippy (taker)",
  "clippy (maker)",
  "clippy (shared-bin)",
  "clippy (daemon-tests)",
  "clippy (tokio-tasks)",
  "clippy (xtras)",
  "clippy (bdk-ext)",
  "clippy (model)",
  "clippy (xtra-bitmex-price-feed)",
  "clippy (btsieve)",
  "clippy (bitmex-stream)",
  "clippy (xtra-libp2p)",
  "clippy (xtra-libp2p-ping)",
  "lint-commits",
  "frontend (maker)",
  "frontend (taker)",
  "test (ubuntu-latest)",
  "test (macos-latest)",
  "smoke_test (ubuntu-latest)",
  "smoke_test (macos-latest)",
  "daemons_arm_build",
]
