status = [
  "formatting",
  "clippy",
  "block-fixup",
  "frontend (maker)",
  "frontend (taker)",
  "test_daemons (ubuntu-latest)",
  "test_daemons (macos-latest)",
  "test_daemons_release_mode (ubuntu-latest)",
  "test_daemons_release_mode (macos-latest)",
  "daemons_arm_build",
]
