status = [
  "formatting",
  "clippy",
  "check_frontend",
  "build_and_test_frontend (maker)",
  "build_and_test_frontend (taker)",
  "test_daemons (ubuntu-latest)",
  "test_daemons (macos-latest)",
  "test_daemons (windows-latest)",
  "daemons_arm_build",
]
