[workspace]
members = ["daemon", "rocket-basicauth", "rust-embed-rocket"]
resolver = "2"

[patch.crates-io]
rocket = { git = "https://github.com/SergioBenitez/Rocket" } # Need to patch rocket dependency of `rocket_basicauth` until there is an official release.
xtra = { git = "https://github.com/comit-network/xtra" } # We need to use unreleased patches.
maia = { git = "https://github.com/comit-network/maia" } # Unreleased
xtra_productivity = { git = "https://github.com/comit-network/xtra-productivity" } # Unreleased
