[workspace]
members = [
  "daemon",
  "rocket-basicauth",
  "rust-embed-rocket",
  "taker",
  "maker",
  "shared-bin",
  "daemon-tests",
  "tokio-tasks",
  "xtras",
  "xtra-bitmex-price-feed",
  "bdk-ext",
  "model",
  "btsieve",
  "bitmex-stream",
  "xtra-libp2p",
  "xtra-libp2p-ping",
]
resolver = "2"

[patch.crates-io]
xtra = { git = "https://github.com/comit-network/xtra" } # We need to use unreleased patches.
maia = { git = "https://github.com/comit-network/maia" } # Unreleased
maia-core = { git = "https://github.com/comit-network/maia" } # Unreleased
xtra_productivity = { git = "https://github.com/comit-network/xtra-productivity" } # Unreleased
