[workspace]
members = [
  "daemon",
  "rocket-basicauth",
  "rust-embed-rocket",
  "taker",
  "maker",
  "shared-bin",
  "daemon-tests",
  "tokio-extras",
  "xtras",
  "xtra-bitmex-price-feed",
  "bdk-ext",
  "model",
  "btsieve",
  "bitmex-stream",
  "xtra-libp2p",
  "xtra-libp2p-ping",
  "xtra-libp2p-offer",
  "xtra-libp2p-rollover",
  "sqlite-db",
  "quiet-spans",
  "vergen-version",
]
resolver = "2"

[patch.crates-io]
xtra = { git = "https://github.com/Restioson/xtra", rev = "285b3e986013888cb68b9219464ef325d2468c2c" } # Unreleased
maia = { git = "https://github.com/comit-network/maia", rev = "9899c9eda1f7685493aecdd7f8ba9124787056bd" }
maia-core = { git = "https://github.com/comit-network/maia", rev = "9899c9eda1f7685493aecdd7f8ba9124787056bd", package = "maia-core" }
xtra_productivity = { git = "https://github.com/comit-network/xtra-productivity", rev = "0bfd589b42a63149221dec7e95aca932875374dd" } # Unreleased
electrum-client = { git = "https://github.com/comit-network/rust-electrum-client/", branch = "do-not-ignore-empty-lines" }
otel-tests = { git = "https://github.com/itchysats/otel-tests/", rev = "4a57d84ad5780c30d09222c56440482d9e722363" } # unreleased

[profile.dev.package.sqlx-macros]
opt-level = 3
