disallowed-methods = [
  "xtra::Address::do_send_async", # discards the return value, possibly swallowing an error
  "xtra::Address::do_send", # discards the return value, possibly swallowing an error
]
