name: CI

on:
  pull_request:
  push:
    branches:
      - 'staging'
      - 'master'

env:
  CARGO_INCREMENTAL: 0

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.0

  gather_workspace_members:
    runs-on: ubuntu-latest
    outputs:
      members: ${{ steps.cargo-metadata.outputs.members }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - id: cargo-metadata
        run: |
          WORKSPACE_MEMBERS=$(cargo metadata --format-version=1 --no-deps | jq -c '.packages | map(.name)')

          echo "::set-output name=members::${WORKSPACE_MEMBERS}"

  clippy:
    needs: gather_workspace_members
    strategy:
      matrix:
        crate: ${{ fromJson(needs.gather_workspace_members.outputs.members) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.crate }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo clippy --all-targets -- -D warnings

  lint-commits:
    runs-on: ubuntu-latest
    if: github.event.ref != 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get all commits on current master
        run: git fetch origin master
      - name: Log all commits we will analyze
        run: git log --pretty=format:%s origin/master..HEAD
      - name: Disallow fixup! commits
        run: git log --pretty=format:%s origin/master..HEAD | grep -zv fixup!
      - name: Disallow squash! commits
        run: git log --pretty=format:%s origin/master..HEAD | grep -zv squash!

  frontend:
    strategy:
      matrix:
        bin: [ maker, taker ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.bin }}-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: ${{ matrix.bin }}-frontend/yarn.lock
      - run: yarn install
      - run: yarn run eslint
      - run: yarn run tsc
      - run: yarn run npmPkgJsonLint .
      - run: yarn run test
      - run: yarn run build

  test_daemons:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo build --tests --workspace
      - run: cargo test --workspace
      # Ignored tests that should be run on the CI - reenable if there are any
      # - run: cargo test --workspace -- --ignored
      - name: Smoke test ${{ matrix.os }} binary
        shell: bash
        run: |
          cargo build --bin maker --bin taker
          
          cargo dev-maker &
          cargo dev-taker &
          sleep 10s # Wait for binaries to start

          curl --fail http://localhost:8000/api/alive
          curl --fail http://localhost:8001/api/alive

  daemons_arm_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v1.3.0

      - name: Install compiler for aarch64 arch
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu
      - run: cargo build --target=aarch64-unknown-linux-gnu --bins
