name: "Create 'preview' release"

on:
  push:
    branches:
      - master

jobs:
  create_release:
    name: Create preview release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOTTY_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Update 'preview' release
        run: |
          gh release delete preview || true # First delete, ignore failures
          gh release create preview --prerelease --title preview
